#!/bin/sh

# Get the required value
API_SERVICE_REMOTE_ENDPOINT=$(grep "FE.APIService.RemoteEndpoint" /etc/ercole/conf.d/20-ercolesetup.toml | cut -d'=' -f2 | sed -e 's/[[:space:]]*"//' | sed -e 's/"[[:space:]]*//')
if [ -z "$API_SERVICE_REMOTE_ENDPOINT" ]; then 
	API_SERVICE_REMOTE_ENDPOINT="/api"
fi

CHART_SERVICE_REMOTE_ENDPOINT=$(grep "FE.ChartService.RemoteEndpoint" /etc/ercole/conf.d/20-ercolesetup.toml | cut -d'=' -f2 | sed -e 's/[[:space:]]*"//' | sed -e 's/"[[:space:]]*//')
if [ -z "$CHART_SERVICE_REMOTE_ENDPOINT" ]; then 
	CHART_SERVICE_REMOTE_ENDPOINT="/chart"
fi

if [ -n "$API_SERVICE_REMOTE_ENDPOINT" ] && [ -n "$CHART_SERVICE_REMOTE_ENDPOINT" ]; then
	echo -e "{\n\t\"APIServiceBaseUrl\":\"${API_SERVICE_REMOTE_ENDPOINT}\",\n\t\"ChartServiceBaseUrl\":\"${CHART_SERVICE_REMOTE_ENDPOINT}\"\n}" > /usr/share/ercole/web/config.json
fi
